Siemens/Siemens/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("favicon.ico"))),
    path('admin/', admin.site.urls),
    path('home/', include('dashboard.urls')),
    path('', include('users.urls'))
]

Siemens/dashboard/urls.py
from django.urls import path
from . import views
from .views import excelImporter

app_name = 'dashboard'

urlpatterns = [
    path('', views.home, name="home"),
    path('excel/<int:file_index>/', views.excelImporter, name="excel_import"),
    path('upload-excel/', views.upload_excel, name='upload_excel'),


    path('data_quality', views.data_quality, name="quality_interface"),



    path('upload-another-excel/', views.upload_another_excel, name='upload_another_excel'),

    path('SRS_Connectivity/', views.active_system_count, name='SRS_Connectivity'),
    path('get_srs_connectivity_chart_data/', views.get_srs_connectivity_chart_data, name='get_srs_connectivity_chart_data'),
    path('get_ruh_readiness_chart_data/', views.get_ruh_readiness_chart_data, name='get_ruh_readiness_chart_data'),
    path('get_Data_Sent_chart_data/', views.get_Data_Sent_chart_data, name='get_Data_Sent_chart_data'),
    path('get_Connection_score_chart_data/', views.get_Connection_score_chart_data, name='get_Connection_score_chart_data'),
    path('CAN24/', views.CAN24, name='CAN24'),

    path('get_srs_connectivity_chart_data2/', views.get_srs_connectivity_chart_data2, name='get_srs_connectivity_chart_data2'),
    path('get_ruh_readiness_chart_data2/', views.get_ruh_readiness_chart_data2, name='get_ruh_readiness_chart_data2'),
    path('get_Data_Sent_chart_data2/', views.get_Data_Sent_chart_data2, name='get_Data_Sent_chart_data2'),
    path('get_Connection_score_chart_data2/', views.get_Connection_score_chart_data2, name='get_Connection_score_chart_data2'),
    path('get_equipment_data/', views.get_equipment_data, name='get_equipment_data'),
    path('get_Can24_Connectable_Systems_chart_data/', views.get_Can24_Connectable_Systems_chart_data, name='get_Can24_Connectable_Systems_chart_data'),
    path('get_CAN24_Data_Sent_chart_data/', views.get_CAN24_Data_Sent_chart_data, name='get_CAN24_Data_Sent_chart_data'),
    path('get_Connected_CAN24_Modul_chart_data/', views.get_Connected_CAN24_Modul_chart_data, name='get_Connected_CAN24_Modul_chart_data'),

    path('fill_missing_countries', views.fillin_missing_country, name='fillMissCountry'),
    path('fill_missing_cst', views.fillin_missing_cst, name='fillMissCst'),

    path('pieCharter/',views.pieCharter,name='pieCharter_africaIB'),

    path('get_equipements_dataAjax/', views.get_equipment_dataAjax, name='get_equipment_dataAjax'),
    path('get_equipment_data_CAN24_Ajax/', views.get_equipment_data_CAN24_Ajax, name='get_equipment_data_CAN24_Ajax'),







    # home redirections paths
   
    path('data_quality', views.data_quality, name="data_quality"),
    path('get_percents/', views.update_dataAjax, name="get_percents"),

    path('africaIB', views.africaIb_interface, name="get_africaIB"),

    # user conf paths
    path('register_pt/', views.registerPartenariat,name ="register_pt"),
    path('registerNewUser/', views.registerNewUser, name="registerNewUser"),
    path('logout/', views.logout_user, name="logout_user"),


    # ajax requests
    path('missing_fl_countries/', views.get_missing_fl_countries, name='missing_fl_countries'),
    path('missing_customer_name/', views.get_missing_customer_name, name='missing_customer_name'),
    path('active_system_count/', views.active_system_count, name='active_system_count'),
    path('get_all_ivknames/', views.get_all_ivknames, name='get_all_ivknames'),
    path('get_equipment_dataAjax2/', views.get_equipment_dataAjax2, name='get_equipment_dataAjax2'),
    # path('get_serialnumber_count/', views.get_serialnumber_count, name='get_serialnumber_count'),
    # path('count_on_stock_substatus/', views.count_on_stock_substatus, name='count_on_stock_substatus'),
    # path('count_active_status/', views.count_active_status, name='count_active_status'),
    # path('count_shipped_substatus/', views.count_shipped_substatus, name='count_shipped_substatus'),

    path('get_serial_data_by_search/', views.get_serial_data_by_search, name='get_serial_data_by_search'),
    path('get_row_data/', views.get_row_data, name='get_row_data'),
    path('filter_data/', views.filter_data, name='filter_data'),
    path('get_filtered_counts/', views.get_filtered_counts, name='get_filtered_counts'),

    # ccr
    path('ccr/', views.ccr_interface, name='ccr'),
    path('update_ccr_data/',views.update_ccr_data, name='update_ccr_data'),
    path('add_ccr_data/',views.add_ccr_data, name='add_ccr_data'),
    

    # manage users
    path('manage_users/', views.manage_user_interface, name='manage_users'),
    path('update_manage_users/', views.update_manage_users, name='update_manage_users'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('reset_user/', views.reset_user, name='reset_user'),
]

Siemens/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('login/', views.index, name="login"),
    path('logUser/', views.logUser, name="logUser"),
    path('activating_account', views.activating_account, name="activating_user")
]

Siemens/dashboard/views.py
import json

from django.contrib.auth import logout
from django.core import serializers
from django.shortcuts import render, redirect
from django.db import connection
from openpyxl import load_workbook
from django.http import JsonResponse
from .models import Quality
from .models import Srs
from .models import Can24
from .models import Partner, Ccr
from users.models import Account, Account
from django.db.models import Count, F, Func, Value, CharField, Max
from datetime import datetime
from datetime import date
from django.core.paginator import Paginator
from django.db.models import Q
from django.db.models import F


def home(request):
    user = request.user
    if not request.user.is_authenticated:
        return redirect('login')

    user_type = user.user_type
    if user_type == 3:
        username = user.partenariat
    else:
        username = {1: "manager", 2: "assistant"}.get(user_type, "unknown")

    print(user.partenariat)
    partenaria = get_user_partenariat(user)
    return render(request, "dashboard/home.html", {"username": username,
                                                   "partenariat": partenaria})


def get_user_partenariat(user):
    user_type = user.user_type
    if user_type == 1 or user_type == 2:
        username = "all"
    elif user_type == 3:
        username = Partner.objects.filter(partnername=user.partenariat).first().partnerid
        # username = user.partenariat
    else:
        username = "unknown"
    return username


def quality_interface(request):
    if not request.user.is_authenticated:
        return redirect('login')

    return render(request, "dashboard/data_quality.html")


def SRS_Connectivity(request):
    results = Srs.objects.values('country_region').annotate(
        equipment_serial_number_count=Count('equipment_serial_number')).order_by('country_region')


    return render(request, 'dashboard/SRS.html',{'countries': results})


def africaIb_interface(request):
    if not request.user.is_authenticated:
        return redirect('login')

    max_week = Quality.objects.aggregate(max_week=Max('week'))['max_week']

    print(max_week)

    user = request.user
    partner = get_user_partenariat(user)

    if(partner != 'all'):
        # Query to count serial numbers for each cstcountry
        results = Quality.objects.filter(
            week=max_week,
            cstcountry__isnull=False,
            servicepartner=partner,
        ).values('cstcountry').annotate(serialnumber_count=Count('serialnumber'))
    else:
        # Query to count serial numbers for each cstcountry
        results = Quality.objects.filter(
            week=max_week,
            cstcountry__isnull=False,  # Ensures cstCountry is not empty
        ).values('cstcountry').annotate(serialnumber_count=Count('serialnumber'))

    return render(request, "dashboard/africa_IB.html", {"partner": partner,"countries": results})


def get_missing_fl_countries(request):
    user = request.user
    partner = get_user_partenariat(user)


    if request.method == "POST":
        filters_data = request.POST.get('filters')
        filters_dict = json.loads(filters_data)
        status_filter = filters_dict['status']
        substatus_filter = filters_dict['substatus']
        week_filter = filters_dict['week']

    if partner == "all":
        missing_fl_countries = Quality.objects.filter(flcountry='').values(
            'id', 'servicepartner', 'materialnumber', 'serialnumber',
            'modality', 'ivkname', 'status', 'substatus', 'flcountry'
        )
    else:
        missing_fl_countries = Quality.objects.filter(
            flcountry='', servicepartner=partner
        ).values(
            'id', 'servicepartner', 'materialnumber', 'serialnumber',
            'modality', 'ivkname', 'status', 'substatus', 'flcountry'
        )

    if status_filter != ['all']:
        missing_fl_countries = missing_fl_countries.filter(status__in=status_filter)
    if substatus_filter != ['all']:
        missing_fl_countries = missing_fl_countries.filter(substatus__in=substatus_filter)
    if week_filter != ['all']:
        missing_fl_countries = missing_fl_countries.filter(week__in=week_filter)

    return JsonResponse(list(missing_fl_countries), safe=False)


def pieCharter(request):
    partner = get_user_partenariat(request.user)
    max_week = Quality.objects.aggregate(max_week=Max('week'))['max_week']

    if(partner != 'all'):
        modalities = Quality.objects.filter(week=max_week,servicepartner=partner, modality__isnull=False).values('modality').distinct().order_by('modality')
        count_total = Quality.objects.filter(week=max_week,servicepartner=partner,serialnumber__isnull=False).values('serialnumber').distinct().count()
        count_by = (Quality.objects.filter(week=max_week,servicepartner=partner,modality__isnull=False).order_by('modality').values('modality').
                    annotate(serialnumber_count=Count('serialnumber', distinct=True)))
    else:
        modalities = Quality.objects.filter(week=max_week,modality__isnull=False).values('modality').distinct().order_by('modality')
        count_total = Quality.objects.filter(week=max_week,serialnumber__isnull=False).values('serialnumber').distinct().count()
        count_by = (Quality.objects.filter(week=max_week,modality__isnull=False).order_by('modality').values('modality').
                    annotate(serialnumber_count=Count('serialnumber', distinct=True)))

    data = {
        'total': count_total,
        'modalities': list(modalities),
        'count': list(count_by),
    }
    return JsonResponse(data)

def fillin_missing_country(request):
    if request.method == "POST":
        idCountry = request.POST.get('id')
        missingCountry = request.POST.get('missingCountry')
        record = Quality.objects.filter(id=idCountry).first()

        if record:
            record.flcountry = missingCountry
            record.save()

        response_data = {'message': 'country not missing anymore'}

        return JsonResponse(response_data)


def fillin_missing_cst(request):
    if request.method == "POST":
        idCst = request.POST.get('id')
        missingCst = request.POST.get('missingCst')
        record = Quality.objects.filter(id=idCst).first()

        if record:
            record.customername = missingCst
            record.save()

        response_data = {'message': 'customer name not missing anymore'}

        return JsonResponse(response_data)


def get_missing_customer_name(request):
    user = request.user
    partner = get_user_partenariat(user)

    if request.method == "POST":
        filters_data = request.POST.get('filters')
        filters_dict = json.loads(filters_data)
        status_filter = filters_dict['status']
        substatus_filter = filters_dict['substatus']
        week_filter = filters_dict['week']

    if partner == "all":
        missing_customer_names = Quality.objects.filter(customername='').values(
            'id', 'servicepartner', 'materialnumber', 'serialnumber',
            'modality', 'ivkname', 'status', 'substatus', 'customername'
        )
    else:
        missing_customer_names = Quality.objects.filter(
            customername='', servicepartner=partner
        ).values(
            'id', 'servicepartner', 'materialnumber', 'serialnumber',
            'modality', 'ivkname', 'status', 'substatus', 'customername'
        )

    # Apply your filtering logic using the status, substatus, and week filters
    if status_filter != ['all']:
        missing_customer_names = missing_customer_names.filter(status__in=status_filter)
    if substatus_filter != ['all']:
        missing_customer_names = missing_customer_names.filter(substatus__in=substatus_filter)
    if week_filter != ['all']:
        missing_customer_names = missing_customer_names.filter(week__in=week_filter)

    return JsonResponse(list(missing_customer_names), safe=False)


def registerPartenariat(request):
    if not request.user.is_authenticated:
        return redirect('login')

    # serializers.serialize("json", Deliveries.objects.all())
    partners = Partner.objects.distinct().order_by('partnername')
    partners_list_se = serializers.serialize("json", Partner.objects.distinct().order_by('partnername'))
    return render(request, "dashboard/register_user.html",
                  {"partenariats": partners, "partenariats_se": partners_list_se})


def registerNewUser(request):
    if request.method == 'POST':
        username = request.POST["email"]
        password = username + "?"
        partenariat = request.POST["partner"]
        email = username + Partner.objects.filter(partnername=partenariat).values('email').first().get('email')

        Account.objects.create_user(email, password, partenariat, 3)

        response_data = {'message': 'User registered successfully'}

        return JsonResponse(response_data)


def ccr_interface(request):
    if not request.user.is_authenticated:
        return redirect('login')
    partenaria = get_user_partenariat(request.user);
    return render(request, 'dashboard/ccr.html', {"partenariat":partenaria})



def update_ccr_data(request):
    user = request.user
    partenariat = get_user_partenariat(user)
    if request.method == 'POST':
        partner_number = request.POST.get('partner_number')
        modality = request.POST.get('modality')
        country = request.POST.get('country')
        search_query = request.POST.get('searchQuery')
        # apply filters
        queryset = Ccr.objects.all().filter(contract_end_date__gt =date.today())
        queryset_quality = Quality.objects.all()

        if partenariat != 'all' or partner_number :
            queryset = queryset.filter(service_partner_id=partner_number) if partenariat == 'all'  else queryset.filter(service_partner_id=partenariat)

            queryset_quality = queryset_quality.filter(servicepartner=partner_number) if partenariat == 'all'  else queryset_quality.filter(servicepartner=partenariat)    

Siemens/dashboard/templates/dashboard/MR_CAN24.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'dashboard/css/styles.css' %}? {% now
    "" %}">
    <title>Africa Connectivity Dashboard</title>
  </head>

  <style>
    body {
      background-image: url("{% static 'dashboard/img/Background.jpg' %}");
      background-repeat: no-repeat;
      background-size: auto;
    }
  </style>

  <body>
    <dialog id="loading">
      <div class="multi-spinner-container">
        <div class="multi-spinner">
          <div class="multi-spinner">
            <div class="multi-spinner">
              <div class="multi-spinner">
                <div class="multi-spinner">
                  <div class="multi-spinner"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </dialog>
    <h1 style="margin-top: 0">Africa Connectivity Dashboard</h1>

    <div class="container">
      <div class="upper-left-container">
        <div class="item active-system-count-container" style="border: none">
          <div id="filter-id" class="filter-container">
            <h3 class="filter-imay">
              Filters: <span id="appliedFilter">Country: Angola</span>
            </h3>
            <button class="removeFilter" onclick="removeFilters()">X</button>
          </div>

          <div class="item-c" style="margin-top: 0; padding: 0 20px 20px">
            <div>
              <p
                class="active-system-count"
                id="count-systems-active-tab"
                style="color: #008b8b; font-size: 50px; margin-bottom: 0"
              >
                16
              </p>
              <h2
                class="active-system-title"
                style="color: #ff8c00; margin-top: 0"
              >
                Systems with Active Connectivity
              </h2>
            </div>
          </div>
        </div>

        <div class="item active-system-chart-container">
          <div class="histogram grid-item">
            <h5 class="item-title">Active System Connectivity</h5>
            <canvas id="histogram4"></canvas>
          </div>
        </div>
      </div>

      <div class="upper-right-container">
        <div class="item srs-connectivity-chart-container">
          <div class="histogram" style="height: 250px">
            <h5 class="item-title">SRS Connectivity</h5>
            <canvas id="histogram1"></canvas>
          </div>
        </div>
        <div class="item ruh-readlines-chart-container">
          <div class="histogram">
            <h5 class="item-title">RUH Readiness</h5>
            <canvas id="histogram2"></canvas>
          </div>
        </div>
        <div class="item srs-data-sent-chart-container">
          <div class="histogram grid-item">
            <h5 class="item-title">SRS Data sent</h5>
            <canvas id="histogram3"></canvas>
          </div>
        </div>
        <div class="item can24-connectable-chart-container">
          <div class="histogram grid-item">
            <h5 class="item-title">CAN 24 Connectable Systems</h5>
            <canvas id="histogram5"></canvas>
          </div>
        </div>
        <div class="item can24-data-sent-chart-container">
          <div class="histogram grid-item">
            <h5 class="item-title">CAN 24 Data Sent</h5>
            <canvas id="histogram6"></canvas>
          </div>
        </div>
        <div class="item connected-can24-chart-container">
          <div class="histogram grid-item">
            <h5 class="item-title">Connected CAN 24 Modul</h5>
            <canvas id="histogram7"></canvas>
          </div>
        </div>
      </div>
      <div class="bottom-left-container" style="background-color: transparent">
        <div class="item" style="height: auto"></div>
      </div>
      <div class="item bottom-right-container">
        <div class="table-wrapper">
          <div class="missing-cst-header">
            <div class="title-and-import">
            <p
              style="
                color: black;
                font-weight: bold;
                margin-left: 10px;
                min-width: 120px;
              "
            >
              Liste equipment
            </p>
            <button
              class="pagination-btn-cst excel"
              onclick="to_excel()"
              style="margin-left: 10px"
            >
              <img
                src="{% static 'dashboard/img/excel_ico.png' %}"
                alt="Excel Logo"
                style="width: 30px"
              />
            </button>
                </div>
            <div class="fl-cst-pagination">
              <button class="pagination-btn-cst left">&lt;</button>
              <span class="pagination-info-cst"
                >1/<span class="missing-cst-total-pages">?</span></span
              >
              <button class="pagination-btn-cst right">&gt;</button>
            </div>
          </div>
          <div class="missing-names-table-container">
            <table class="ms-names-table" style="display: block">
              <thead>
                <tr>
                  <th class="ms-names-table-header">
                    Equipment service partner ID
                  </th>
                  <th class="ms-names-table-header">
                    Equipment service partner text
                  </th>
                  <th class="ms-names-table-header">Country Region</th>
                  <th class="ms-names-table-header">Func Location Name</th>
                  <th class="ms-names-table-header">
                    Equipment material number
                  </th>
                  <th class="ms-names-table-header">Equipment serial number</th>
                  <th class="ms-names-table-header">Material IVK name</th>
                  <th class="ms-names-table-header">SRS Connectivity</th>
                  <th class="ms-names-table-header">RUH Readiness</th>
                  <th class="ms-names-table-header">Data Sent</th>
                </tr>
              </thead>
              <tbody class="ms-names-table-body">


              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <script>
      loading.showModal();
    </script>
 
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.17.4/xlsx.full.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2"></script>
    <script>
      let srs_connectivity_chart_url =
        "{% url 'dashboard:get_srs_connectivity_chart_data2' %}";
      let ruh_readiness_chart_url =
        "{% url 'dashboard:get_ruh_readiness_chart_data2' %}";
      let data_sent_chart_url =
        "{% url 'dashboard:get_Data_Sent_chart_data2' %}";
      let connection_score_chart_url =
        "{% url 'dashboard:get_Connection_score_chart_data2' %}";
      let can24_connectable_systems_chart_url =
        "{% url 'dashboard:get_Can24_Connectable_Systems_chart_data' %}";
      let can24_data_sent_chart_url =
        "{% url 'dashboard:get_CAN24_Data_Sent_chart_data' %}";
      let connected_can24_modul_chart_url =
        "{% url 'dashboard:get_Connected_CAN24_Modul_chart_data' %}";

      let missing_customerName_URL =
        "{% url 'dashboard:get_equipment_data_CAN24_Ajax' %}";
    </script>

    {% csrf_token %}
    <script src="{% static 'dashboard/js/can24.js' %}"></script>

  
  </body>
</html>

Siemens/dashboard/templates/dashboard/excel_import1.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Importer</title>
    <link rel="stylesheet" href="{% static 'dashboard/css/excel.css' %}">
</head>

<body>
    <div class="container">
        <div class="grp">
            <label class="container-title" > Import Installed base excel file</label>
            <input  type="file" id="files" style="display: none" accept=".xlsx, .xls"/>
            <label id="importer" class="importer before" for="files">Click here</label>
            <label class="importer after" style="display: none">the file <i class="importedFilename">placeholder</i> is imported</label>
            <a class="submitter">Save</a>
        </div>
    </div>

    <dialog id="load_dialog">
      <div class="lds-hourglass"></div>
    </dialog>

    <dialog id="message_dialog">
            <p class="message">Message</p>
    </dialog>

</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script>
    const url = "{% url 'dashboard:upload_excel' %}"
</script>
{% csrf_token %}
<script src="{% static 'dashboard/js/excel.js' %}"></script>

</html>

Siemens/dashboard/templates/dashboard/excel_import2.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Importer</title>
    <link rel="stylesheet" href="{% static 'dashboard/css/excel.css' %}">
</head>

<body>
    <div class="container">
        <div class="grp">
            <label class="container-title" > importer votre fichier Excel</label>
            <input  type="file" id="files" style="display: none" accept=".xlsx, .xls"/>
            <label id="importer" class="importer before" for="files">Click ici</label>
            <label class="importer after" style="display: none">le fichier <i class="importedFilename">placeholder</i> est importe</label>
            <a class="submitter">Envoyer</a>
        </div>
    </div>

    <dialog id="load_dialog">
      <div class="lds-hourglass"></div>
    </dialog>

    <dialog id="message_dialog">
            <p class="message">Message</p>
    </dialog>

</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
{% csrf_token %}
<script>
    const url = "{% url 'dashboard:upload_another_excel' %}"
</script>
<script src="{% static 'dashboard/js/excel.js' %}"></script>

</html>

Siemens/dashboard/templates/dashboard/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static "dashboard/css/home.css" %}?{% now "U" %}">
  <title>Home</title>
</head>

<style>
    body{
        background-image: url("{% static 'dashboard/img/Background.jpg' %}");
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>
<body>
  <nav class="navbar">
    <div class="nav-left">
      <img src="{% static "users/img/Siemens_Healthineers_logo.png" %}" style="padding:4px;border-radius:.6em;background-color:white;scale: 1;width: 150px; background-color:transparent;" alt="Logo">
    </div>
    <ul class="nav-list">
        {% if partenariat == "all" %}
      <li style="display: flex;cursor: pointer">
          <img src="{% static "dashboard/img/upload-icon.png" %}" width="25px">
          <a href="{% url 'dashboard:excel_import' file_index=1 %}" style="padding:6px;color : black">Quality Excel</a>
      </li>
        <li style="display: flex;cursor: pointer">
          <img src="{% static "dashboard/img/upload-icon.png" %}" width="25px">
          <a href="{% url 'dashboard:excel_import' file_index=2 %}" style="padding:6px;color : black">SRS/Can24 Excel</a>
      </li>
      {% endif %}
      <li class="dropdown">
        <button class="dropbtn" style="background-color: transparent;  %}">{{ username }}</button>
        <div class="dropdown-content">
            {% if partenariat == "all" %}
        {% comment %} <a href="#option1">
            <img src="{% static "dashboard/img/profile_icon.png" %}" alt="Icon 1" width="30px">
        </a> {% endcomment %}
        <a href="register_pt/">
            <img src="{% static "dashboard/img/add_user_icon.png" %}" alt="Icon 2" width="30px">
        </a>
        <a href="manage_users/">
            <img src="{% static "dashboard/img/manage_users_icon.png" %}" alt="Icon 3" width="30px">
        </a>
            {% endif %}
        <a onclick="logout()">
            <img src="{% static "dashboard/img/logout icon.png" %}" alt="Icon 3" width="30px">
        </a>
    </div>
      </li>
    </ul>
  </nav>

  <div class="content">
        <a class="redirection-links" href="{% url "dashboard:get_africaIB" %}"><div class="card card1"> <p>Africa_IB</p></div></a>
        <a class="redirection-links" href="{% url "dashboard:quality_interface" %}"><div class="card card2"> <p>Data Quality</p></div></a>
        <a class="redirection-links" href="{% url "dashboard:SRS_Connectivity" %}"><div class="card card3"> <p>SRS Connectivity</p></div></a>
        <a class="redirection-links" href="{% url "dashboard:CAN24" %}"><div class="card card4"> <p>MR CAN24</p></div></a>
        <a class="redirection-links" href="{% url "dashboard:ccr" %}"><div class="card card5"> <p>Contrat de service</p></div></a>

  </div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
{% csrf_token %}
<script>

    function logout() {
        const csrfToken = $('[name=csrfmiddlewaretoken]').val();
        $.ajax({
            type: "POST",
            url: "{% url 'dashboard:logout_user' %}",
            data: {
                csrfmiddlewaretoken: csrfToken
            },
            success: function(response) {
                window.location.href = "{% url 'login' %}";
            },
            error: function() {
                alert("Logout failed.");
            }
        });
    }
</script>
</html>

Siemens/dashboard/templates/dashboard/manage_users.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Manage users</title>
    <link rel="stylesheet" href="{% static 'dashboard/css/manage_users.css' %}?{% now "U" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
</head>
<body>
    <h1>User Management</h1>

    <div class="search-cn">
        <button id="add-user-btn">Add User</button>
        <input type="text" id="search-input" placeholder="Search">
    <button value="" id="search-btn"><i class="fa fa-search" aria-hidden="true"></i>
    </button>
    </div>


    <div class="table-cn">
    <div class="table-wrapper">

        <table id="user-table">
            <thead>
                <tr>
                    <th>Email</th>
                    <th>Partner</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody id="table-tbody">

            </tbody>
        </table>
    </div>
    </div>
</body>
{% csrf_token %} 
<script>
    let update_manage_users_url = "{% url 'dashboard:update_manage_users' %}"
    let delete_user_url = "{% url 'dashboard:delete_user' %}"
    let add_user_url = "{% url 'dashboard:register_pt' %}"
    let reset_user_url = "{% url 'dashboard:reset_user' %}"

    
</script>
<script src="{% static 'dashboard/js/manage_users.js' %}"></script>

</html>